# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/borneo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),borneo)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,7a24375434bd43eef7af9df0f1670dd5eb98ae98)
$(call add-radio-file-sha1-checked,radio/modem.img,b2a28cbe1592128f7770436e965de53038ccc778)
$(call add-radio-file-sha1-checked,radio/abl.img,f3d052e01ac6105b7d8c0a231e5dcf337d1a9429)
$(call add-radio-file-sha1-checked,radio/devcfg.img,806825f0b8cd2a5f9120cf2df1f6277b0873b8db)
$(call add-radio-file-sha1-checked,radio/dsp.img,a4d96325a5d65cc91374e29ba29d7bbf19f50bd7)
$(call add-radio-file-sha1-checked,radio/fsg.img,7b37b00b73ebf9bacdf296e05ca98670952d7599)
$(call add-radio-file-sha1-checked,radio/hyp.img,f840956d5a98ff043c5fc6329481f1da36611b6f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,0f7b9a58f1ea80bc1785cc20d61d6e36252c344e)
$(call add-radio-file-sha1-checked,radio/logo.img,b0b5620b385e95d8f7a386fbff7f7c108b7a24cf)
$(call add-radio-file-sha1-checked,radio/prov.img,649559b89f377b831b0f5f1391c175aebdcc8860)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2e2f15a3b22cbdc6fc805c414dad6ad68510274d)
$(call add-radio-file-sha1-checked,radio/rpm.img,71d2d393cb310d2273b4505037209125bf6b028d)
$(call add-radio-file-sha1-checked,radio/storsec.img,1242fe8610d3222409649fe2dd6844302ec2bbc1)
$(call add-radio-file-sha1-checked,radio/tz.img,45c557ca3e5b7a043ffd568c7dca653d17568895)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,108cf6f7083bd025d850fe45952351fa4b47b9f2)
$(call add-radio-file-sha1-checked,radio/xbl.img,2b643121f19dbfb75ec7497ddd01e9542433e5b3)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,1b9afcc27d110fdb561aea4543d206dfe85ae914)

endif
